#!/usr/bin/env bash
# gitlab-helpers.sh - Shared helper functions for the spec-kit GitLab extension
set -euo pipefail

# ============================================================================
# Load configuration
# ============================================================================

load_gitlab_config() {
  local config_file="${1:-.specify/extensions/gitlab/gitlab-config.yml}"
  local local_override="${config_file%.yml}.local.yml"

  if [[ -f "$local_override" ]]; then
    config_file="$local_override"
  fi

  if [[ ! -f "$config_file" ]]; then
    echo "ERROR: GitLab configuration not found: $config_file" >&2
    echo "Run 'specify extension add --dev ~/spec-kit-gitlab/'." >&2
    return 1
  fi

  # Extract values from config (simple YAML parsing)
  GITLAB_URL="${GITLAB_URL:-$(grep '^\s*url:' "$config_file" | head -1 | sed 's/.*url:\s*//' | tr -d '"' | tr -d "'")}"
  GITLAB_PROJECT="${GITLAB_PROJECT:-$(grep '^\s*project:' "$config_file" | head -1 | sed 's/.*project:\s*//' | tr -d '"' | tr -d "'")}"
  GITLAB_STORY_LABEL="$(grep '^\s*story_label:' "$config_file" | head -1 | sed 's/.*story_label:\s*//' | tr -d '"' | tr -d "'")"
  GITLAB_TASK_LABEL="$(grep '^\s*task_label:' "$config_file" | head -1 | sed 's/.*task_label:\s*//' | tr -d '"' | tr -d "'")"
  GITLAB_SPECKIT_LABEL="$(grep '^\s*speckit_label:' "$config_file" | head -1 | sed 's/.*speckit_label:\s*//' | tr -d '"' | tr -d "'")"
  GITLAB_PRIORITY_TO_LABEL="$(grep '^\s*priority_to_label:' "$config_file" | head -1 | sed 's/.*priority_to_label:\s*//' | tr -d ' ')"
  GITLAB_LINK_TASKS="$(grep '^\s*link_tasks_to_stories:' "$config_file" | head -1 | sed 's/.*link_tasks_to_stories:\s*//' | tr -d ' ')"
  GITLAB_FEATURE_TO_MILESTONE="$(grep '^\s*feature_to_milestone:' "$config_file" | head -1 | sed 's/.*feature_to_milestone:\s*//' | tr -d ' ')"
  GITLAB_FEATURE_TO_ISSUE="$(grep '^\s*feature_to_issue:' "$config_file" | head -1 | sed 's/.*feature_to_issue:\s*//' | tr -d ' ')"
  GITLAB_FEATURE_LABEL="$(grep '^\s*feature_label:' "$config_file" | head -1 | sed 's/.*feature_label:\s*//' | tr -d '"' | tr -d "'")"

  # Defaults
  GITLAB_STORY_LABEL="${GITLAB_STORY_LABEL:-user-story}"
  GITLAB_TASK_LABEL="${GITLAB_TASK_LABEL:-task}"
  GITLAB_SPECKIT_LABEL="${GITLAB_SPECKIT_LABEL:-spec-kit}"
  GITLAB_PRIORITY_TO_LABEL="${GITLAB_PRIORITY_TO_LABEL:-true}"
  GITLAB_LINK_TASKS="${GITLAB_LINK_TASKS:-true}"
  GITLAB_FEATURE_TO_MILESTONE="${GITLAB_FEATURE_TO_MILESTONE:-true}"
  GITLAB_FEATURE_TO_ISSUE="${GITLAB_FEATURE_TO_ISSUE:-true}"
  GITLAB_FEATURE_LABEL="${GITLAB_FEATURE_LABEL:-feature}"

  # Validation
  if [[ -z "$GITLAB_URL" || "$GITLAB_URL" == '${GITLAB_URL}' ]]; then
    echo "ERROR: GITLAB_URL is not configured. Set the URL in gitlab-config.yml or as an environment variable." >&2
    return 1
  fi
  if [[ -z "$GITLAB_PROJECT" || "$GITLAB_PROJECT" == '${GITLAB_PROJECT}' ]]; then
    echo "ERROR: GITLAB_PROJECT is not configured." >&2
    return 1
  fi
}

# ============================================================================
# glab wrapper
# ============================================================================

glab_cmd() {
  # Runs glab with the correct host
  GITLAB_HOST="$GITLAB_URL" glab "$@" --repo "$GITLAB_PROJECT"
}

glab_create_issue() {
  local title="$1"
  local description="${2:-}"
  local labels="${3:-}"
  local issue_type="${4:-}"
  local milestone="${5:-}"

  local args=(issue create --title "$title" --yes)

  if [[ -n "$description" ]]; then
    args+=(--description "$description")
  fi
  if [[ -n "$labels" ]]; then
    args+=(--label "$labels")
  fi
  if [[ -n "$issue_type" ]]; then
    args+=(--type "$issue_type")
  fi
  if [[ -n "$milestone" ]]; then
    args+=(--milestone "$milestone")
  fi

  glab_cmd "${args[@]}" 2>&1
}

glab_list_issues() {
  local labels="${1:-$GITLAB_SPECKIT_LABEL}"
  local state="${2:-all}"

  glab_cmd issue list --label "$labels" --state "$state" --output json 2>/dev/null || echo "[]"
}

glab_view_issue() {
  local issue_number="$1"
  glab_cmd issue view "$issue_number" --output json 2>/dev/null
}

glab_add_relation() {
  local child_issue="$1"
  local parent_issue="$2"
  # Links the child issue to the parent issue
  glab_cmd issue relation add "$child_issue" --related "$parent_issue" 2>/dev/null || true
}

# ============================================================================
# Mapping file management
# ============================================================================

MAPPING_FILE=".gitlab-mapping.yml"

init_mapping_file() {
  local feature_dir="$1"
  local mapping_path="$feature_dir/$MAPPING_FILE"

  if [[ ! -f "$mapping_path" ]]; then
    cat > "$mapping_path" << 'YAML'
# GitLab Issue Mapping - automatically generated by the spec-kit GitLab extension
# Format: spec-kit ID → GitLab issue number and URL
feature: ""
stories: {}
tasks: {}
YAML
  fi
  echo "$mapping_path"
}

read_mapping() {
  local mapping_path="$1"
  local section="$2"  # "stories" or "tasks"
  local id="$3"

  if [[ ! -f "$mapping_path" ]]; then
    return 1
  fi

  # Reads the issue number for a given ID from the mapping file
  local in_section=false
  while IFS= read -r line; do
    if [[ "$line" =~ ^${section}: ]]; then
      in_section=true
      continue
    fi
    if [[ "$in_section" == true ]]; then
      if [[ "$line" =~ ^[a-z] ]]; then
        break  # A new section begins
      fi
      if [[ "$line" =~ ^[[:space:]]+${id}: ]]; then
        echo "$line" | sed "s/.*${id}:\s*//" | tr -d '"' | tr -d "'"
        return 0
      fi
    fi
  done < "$mapping_path"

  return 1
}

write_mapping() {
  local mapping_path="$1"
  local section="$2"  # "stories" or "tasks"
  local id="$3"
  local issue_number="$4"
  local issue_url="${5:-}"

  if [[ ! -f "$mapping_path" ]]; then
    init_mapping_file "$(dirname "$mapping_path")" > /dev/null
  fi

  local entry="  ${id}: \"#${issue_number}"
  if [[ -n "$issue_url" ]]; then
    entry+=" ${issue_url}"
  fi
  entry+="\""

  # Check whether the entry already exists
  if grep -q "^\s*${id}:" "$mapping_path" 2>/dev/null; then
    # Update the existing entry
    sed -i.bak "s|^\(\s*\)${id}:.*|${entry}|" "$mapping_path"
    rm -f "${mapping_path}.bak"
  else
    # Insert a new entry after the section header
    sed -i.bak "/^${section}:/a\\
${entry}" "$mapping_path"
    rm -f "${mapping_path}.bak"
  fi
}

# ============================================================================
# Extract the issue URL from glab output
# ============================================================================

extract_issue_url() {
  local output="$1"
  echo "$output" | grep -oE 'https?://[^ ]+/issues/[0-9]+' | head -1
}

extract_issue_number() {
  local output="$1"
  echo "$output" | grep -oE '/issues/([0-9]+)' | head -1 | grep -oE '[0-9]+'
}

# ============================================================================
# Priority mapping
# ============================================================================

priority_to_label() {
  local priority="$1"
  case "$priority" in
    P1|p1) echo "priority::1" ;;
    P2|p2) echo "priority::2" ;;
    P3|p3) echo "priority::3" ;;
    P4|p4) echo "priority::4" ;;
    *) echo "" ;;
  esac
}

# ============================================================================
# Milestone management
# ============================================================================

get_feature_name() {
  local feature_dir="$1"
  # Feature name = name of the feature directory
  basename "$feature_dir"
}

glab_find_milestone() {
  # Looks up a milestone by title, returns the milestone ID
  local title="$1"
  glab_cmd api "projects/:id/milestones?title=$(printf '%s' "$title" | jq -sRr @uri)" 2>/dev/null \
    | jq -r ".[0].id // empty" 2>/dev/null || true
}

glab_create_milestone() {
  # Creates a new milestone and returns the ID
  local title="$1"
  local description="${2:-Automatically created by spec-kit for feature: $title}"
  glab_cmd api "projects/:id/milestones" -f "title=$title" -f "description=$description" 2>/dev/null \
    | jq -r ".id" 2>/dev/null
}

glab_ensure_milestone() {
  # Finds or creates a milestone, returns the title (for the --milestone flag)
  local feature_name="$1"

  local milestone_id
  milestone_id="$(glab_find_milestone "$feature_name")"

  if [[ -z "$milestone_id" ]]; then
    milestone_id="$(glab_create_milestone "$feature_name")"
    if [[ -n "$milestone_id" ]]; then
      echo "Milestone '$feature_name' created (ID: $milestone_id)" >&2
    else
      echo "WARN: Could not create milestone '$feature_name'" >&2
      return 1
    fi
  fi

  # glab issue create --milestone expects the title
  echo "$feature_name"
}

# ============================================================================
# Feature issue mapping
# ============================================================================

read_feature_mapping() {
  local mapping_path="$1"

  if [[ ! -f "$mapping_path" ]]; then
    return 1
  fi

  local value
  value="$(grep '^\s*feature:' "$mapping_path" | head -1 | sed 's/.*feature:\s*//' | tr -d '"' | tr -d "'")"

  if [[ -n "$value" ]]; then
    echo "$value"
    return 0
  fi

  return 1
}

write_feature_mapping() {
  local mapping_path="$1"
  local issue_number="$2"
  local issue_url="${3:-}"

  if [[ ! -f "$mapping_path" ]]; then
    init_mapping_file "$(dirname "$mapping_path")" > /dev/null
  fi

  local entry="feature: \"#${issue_number}"
  if [[ -n "$issue_url" ]]; then
    entry+=" ${issue_url}"
  fi
  entry+="\""

  # Check whether the feature entry already exists
  if grep -q '^\s*feature:' "$mapping_path" 2>/dev/null; then
    sed -i.bak "s|^\(\s*\)feature:.*|${entry}|" "$mapping_path"
    rm -f "${mapping_path}.bak"
  else
    # Insert before stories:
    sed -i.bak "/^stories:/i\\
${entry}" "$mapping_path"
    rm -f "${mapping_path}.bak"
  fi
}

extract_feature_issue_number() {
  local mapping_value="$1"
  # Extracts the issue number from "#232 https://..." or "#232"
  echo "$mapping_value" | grep -oE '#[0-9]+' | head -1 | tr -d '#'
}

# ============================================================================
# Close / reopen issue
# ============================================================================

glab_close_issue() {
  local issue_number="$1"
  glab_cmd issue close "$issue_number" 2>&1
}

glab_reopen_issue() {
  local issue_number="$1"
  glab_cmd issue reopen "$issue_number" 2>&1
}

extract_mapping_issue_number() {
  local mapping_value="$1"
  # Extracts the issue number from "#42 https://..." or "#42"
  echo "$mapping_value" | grep -oE '#[0-9]+' | head -1 | tr -d '#'
}
